# Generated by Django 5.2.8 on 2025-11-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsnz', '0002_alter_player_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
